language: python
python:
- 2.7
- 3.3
- 3.4
- 3.5
- 3.6
install:
- pip install codecov
script:
- coverage run -m unittest discover -s test
after_success:
- codecov
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  server: https://pypi.python.org/pypi
  user: marceljanerfont
  password:
    secure: "Ek7gpYLj0xy47seq7onqfvSdo3zCPDH8A7y/0omxfI8CTG0OVTYgHj9WVzajhOaXeDIOxAL5G1L6jKi1hPuz7xTibayYUkJt6JMx8PoaPrAEn4Mz3FH4CAtdYrVTOLvj28tAm1YUHfd/bI/pkoDtWB4tBzXkoaBF1nYEEXDjju//G+pYWCQVZ170oefIYkGnea9UjIduFpTymw5gi4KRXlLjL2zFDJR4g0KWu5VIiMZsBpBViA4+s39WKVIU6+3jy8BTfFJgECzot+7V9leGQoSA9XiqgrOIb6tHOiZsQlRBErhqPHOJbh5x99dbwWrHKMorif6W52sVPDCtrXYfHnBk/nXn74U3heghydfjCebwf1KMg0XSP1Zo5t571dNoZ3n3BP6O2eWHa1s7ZzsuXlbLB0DGo/4/xS+qkU/64BDRjA6AeGEw95Lw5VkmtUNs09stGE4IVeKGoL2ELR9JQHiIQYcRPQ/ffa3b0Jiz2RP85+0MSyfyXkuhlEZM4/nMLCPG52qV2aHJWSLbvsEt5VNs2bJdMBRJ8XRMNVTce4JsFda+Hrwoy+I0oTclC4kfJYZQxyLHJ6Zmu5DdUDWnElQtcPr0TfgnM3rRAnxoZz/SDBByf3jOpkcog4ys8R8ObUXNJcp4qVA/ysLepuQ4YMnThh9J31MrbqL/vZeJw1Q="
  on:
    python: 2.7
    tags: false
    branch: production
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  server: https://testpypi.python.org/pypi
  user: marceljanerfont
  password:
    secure: "Ek7gpYLj0xy47seq7onqfvSdo3zCPDH8A7y/0omxfI8CTG0OVTYgHj9WVzajhOaXeDIOxAL5G1L6jKi1hPuz7xTibayYUkJt6JMx8PoaPrAEn4Mz3FH4CAtdYrVTOLvj28tAm1YUHfd/bI/pkoDtWB4tBzXkoaBF1nYEEXDjju//G+pYWCQVZ170oefIYkGnea9UjIduFpTymw5gi4KRXlLjL2zFDJR4g0KWu5VIiMZsBpBViA4+s39WKVIU6+3jy8BTfFJgECzot+7V9leGQoSA9XiqgrOIb6tHOiZsQlRBErhqPHOJbh5x99dbwWrHKMorif6W52sVPDCtrXYfHnBk/nXn74U3heghydfjCebwf1KMg0XSP1Zo5t571dNoZ3n3BP6O2eWHa1s7ZzsuXlbLB0DGo/4/xS+qkU/64BDRjA6AeGEw95Lw5VkmtUNs09stGE4IVeKGoL2ELR9JQHiIQYcRPQ/ffa3b0Jiz2RP85+0MSyfyXkuhlEZM4/nMLCPG52qV2aHJWSLbvsEt5VNs2bJdMBRJ8XRMNVTce4JsFda+Hrwoy+I0oTclC4kfJYZQxyLHJ6Zmu5DdUDWnElQtcPr0TfgnM3rRAnxoZz/SDBByf3jOpkcog4ys8R8ObUXNJcp4qVA/ysLepuQ4YMnThh9J31MrbqL/vZeJw1Q="
  on:
    python: 3.6
    tags: false
    branch: master
